Update Aliases readme
jwu910/liferay-ui-toolbox pull request #11
Opened 2017-11-02 00:07 UTC by jwu910

Hi @jwu910,<br><br>Attached is the fix for [](http://issues.liferay.com/browse/).<br><br>Let me know if you have any questions. Thanks.

2017-11-02 00:07 UTC, jwu910 commented
@alexandervalencia

2017-11-02 17:58 UTC, alexandervalencia requested changes

2017-11-02 17:58 UTC, alexandervalencia commented on aliases/README.md
> +We have set up each file to have each alias disabled by default. Unfortunately, this would require you to read through the file to decide what aliases you would like to enable. This is the best way n
How about, "We have set up each file to have each alias disabled by default. This means you are required to read through the file and decide what aliases you would like to enable. This is the best way not to interupt your workflow by accidentally overwriting any possible shared alias names."

2017-11-02 17:58 UTC, alexandervalencia commented on aliases/README.md
> +	- Aliases can be enabled by uncommenting the alias(removing the `#` preceeding the alias)
"Be sure not to uncomment the actual comments left to help explain what the alias does."

2017-11-06 16:43 UTC, alexandervalencia commented
🚀  👍

2017-11-06 17:23 UTC, merged